---
title: Automated Data Pipeline with GitHub Pages CSV Upload
theme: jekyll-theme-minimal
---

# Automated Data Pipeline with GitHub Pages CSV Upload

This project demonstrates an end-to-end data pipeline that begins with uploading a CSV file through a GitHub Pages site, processes the data, and finally visualizes it using Metabase. The pipeline consists of the following steps:

1. Upload a CSV file to the GitHub Pages site.
2. Ingest the CSV data using a Flask app running on Heroku, which processes and cleans the data.
3. Load the processed data into Google Sheets.
4. Sync the data to Snowflake using Fivetran.
5. Transform the data using dbt.
6. Visualize the data with Metabase.

The project utilizes a bash script to automate the integration of Flask, Docker, and Heroku, streamlining the deployment process and enabling a seamless data pipeline. By leveraging the power of these three components, the script provides the following key benefits for this use case:

1. **Flask API Automation:** The script sets up a Flask app to handle data processing and communication between the GitHub Pages site, Google Sheets, and the rest of the pipeline components, simplifying the steps required to create the necessary API endpoints.
2. **Docker Containerization Automation:** The script automatically generates a Dockerfile that creates a containerized environment for the application, ensuring consistency, portability, and reproducibility across different stages. This eliminates manual installation of dependencies and simplifies deployment across platforms.
3. **Heroku Deployment Automation:** The script takes care of deploying the containerized Flask app on Heroku, a platform-as-a-service (PaaS) that manages infrastructure and operations. This enables developers to focus on building features and functionality, without worrying about deployment details.
4. **GitHub Integration:** The script automates the process of creating a new GitHub repository, initializing the repository with necessary files, and pushing the code. This allows for easy version control, collaboration, and showcasing of the project.
